/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.Blackjack;

import Resources.Java.Blackjack.AllCards;
import Object.Blackjack.CardList;
import static Views.Shared.Main.getImage;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Dave van Rijn, Student 500714558, Klas IS202
 */
public class DealGame extends javax.swing.JPanel {
    
    private CardList cards;
    private final CardList PICKED_CARDS;
    private final CardList PLAYER_CARDS;
    private final CardList SPLIT_CARDS;
    private final CardList DEALER_CARDS;
    
    private boolean sevenCards;
    private boolean splitSevenCards;
    private boolean blackjack;
    private boolean dealerBlackjack;
    private boolean tooMuch;
    private boolean splitTooMuch;
    private boolean dealerTooMuch;
    
    private int wager;
    /**
     * Creates new form DealGame
     */
    public DealGame(int wager) {
        initComponents();
        initComps();
        
        this.wager = wager;
        
        cards = AllCards.getShuffledCards();
        PICKED_CARDS = new CardList();
        PLAYER_CARDS = new CardList();
        SPLIT_CARDS = new CardList();
        DEALER_CARDS = new CardList();
    }
    
    private void initComps(){
        background.setIcon(new ImageIcon(getImage("backgroundBlackjack")));
        layer.removeAll();
        layer.add(background);
        layer.moveToFront(background);
    }
    
    private void doubleBet(){
        wager *= 2;
    }
    
    private void clearGame(){
        PICKED_CARDS.clear();
        PLAYER_CARDS.clear();
        SPLIT_CARDS.clear();
        DEALER_CARDS.clear();
        cards = AllCards.getShuffledCards();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        layer = new javax.swing.JLayeredPane();
        background = new javax.swing.JLabel();

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/backgroundBlackjack.png"))); // NOI18N

        layer.setLayer(background, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layerLayout = new javax.swing.GroupLayout(layer);
        layer.setLayout(layerLayout);
        layerLayout.setHorizontalGroup(
            layerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layerLayout.createSequentialGroup()
                .addComponent(background)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layerLayout.setVerticalGroup(
            layerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(layer)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(layer)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Swing components
    private JLabel lblPlayer;
    private JLabel lblDealer;
    private JLabel lblSplit;
    private JButton btnHit;
    private JButton btnSplit;
    private JButton btnDouble;
    private JButton btnStop;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLayeredPane layer;
    // End of variables declaration//GEN-END:variables
}
