/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Casino;

import Blackjack.PlaceBet;
import Roulette.Betting;
import java.awt.Cursor;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author Dave van Rijn, Student 500714558, Klas IS202
 */
public class Startpage extends javax.swing.JPanel {

    /**
     * Creates new form Startpage
     */
    public Startpage() {
        initComponents();
        JButton btnRoulette = new JButton(
                new ImageIcon(getClass().getResource("/Img/btnRoulette.png")));
        JButton btnBlackjack = new JButton(
                new ImageIcon(getClass().getResource("/Img/btnBlackjack.png")));
        JButton btnLogout = new JButton(
                new ImageIcon(getClass().getResource("/Img/btnLogout.png")));
        JButton btnPlayer = new JButton(
                new ImageIcon(getClass().getResource("/Img/btnPlayer.png")));
        
        btnRoulette.setBounds(262, 180, 275, 110);
        btnRoulette.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        btnBlackjack.setBounds(262, 320, 275, 110);
        btnBlackjack.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        btnLogout.setBounds(635, 20, 124, 40);
        btnLogout.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        btnPlayer.setBounds(491, 20, 124, 40);
        
        btnRoulette.addMouseListener(new MouseAdapter(){
            @Override
            public void mousePressed(MouseEvent e){
                Main.setPanel(new Betting());
            }
        });
        
        btnBlackjack.addMouseListener(new MouseAdapter(){
            @Override
            public void mousePressed(MouseEvent e){
                Main.setPanel(new PlaceBet());
            }
        });
        
        btnLogout.addMouseListener(new MouseAdapter(){
           @Override
           public void mouseClicked(MouseEvent e){
               Player.deleteCurrentPlayer();
               Main.setPanel(new Login());
           }
        });
        
        btnPlayer.addMouseListener(new MouseAdapter(){
           @Override
           public void mousePressed(MouseEvent e){
               Main.setPanel(new PlayerPage());
           }
        });
        
        layer.add(btnRoulette);
        layer.add(btnBlackjack);
        layer.add(btnLogout);
        layer.add(btnPlayer);
        
        layer.moveToFront(lblBackground);
        layer.moveToFront(btnRoulette);
        layer.moveToFront(btnBlackjack);
        layer.moveToFront(btnLogout);
        layer.moveToFront(btnPlayer);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        layer = new javax.swing.JLayeredPane();
        lblBackground = new javax.swing.JLabel();

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/backgroundStartpage.png"))); // NOI18N

        javax.swing.GroupLayout layerLayout = new javax.swing.GroupLayout(layer);
        layer.setLayout(layerLayout);
        layerLayout.setHorizontalGroup(
            layerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layerLayout.setVerticalGroup(
            layerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layer.setLayer(lblBackground, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(layer)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(layer)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane layer;
    private javax.swing.JLabel lblBackground;
    // End of variables declaration//GEN-END:variables
}
